import {test}from'node:test';
import assert from'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync}from'node:fs';
import path from'node:path';
import {pathToFileURL}from'node:url';
import ts from'typescript';
import * as model from'../dist-server/shared/model.js';
const root=mkdtempSync(path.resolve('.test-temp','canvas-render-'));
async function load(file){const source=readFileSync(file,'utf8').replace(/(['"])\.\.\/shared\/([^'"]+)\1/g,(_,q,name)=>q+pathToFileURL(path.resolve('dist-server/shared',name)).href+q);const out=path.join(root,path.basename(file,'.ts')+'.mjs');writeFileSync(out,ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);return import(pathToFileURL(out).href);}
const {canvasAssets,renderCanvasAsset}=await load('web/canvas-media.ts');
const {candidatePanel}=await load('web/candidate-panel.ts');
const {modelPicker,catalogFeedback}=await load('web/model-picker.ts');
test('model picker renders a true selection list and preserves a saved local model outside the remote catalog',()=>{const html=modelPicker(['video.one','video.two'],'fixture.video','model-id');assert.match(html,/select name="catalog-model-choice"/);assert.match(html,/data-target="model-id"/);assert.match(html,/value="video.two"/);assert.match(html,/value="fixture.video" selected/);assert.match(html,/未在目录验证/);assert.equal((html.match(/value="fixture.video"/g)||[]).length,1);});
test('model catalog errors and unclassified results are distinct and never masquerade as selectable verified models',()=>{const failed=catalogFeedback('local','fetch failed',0,0);assert.match(failed,/role="alert"/);assert.match(failed,/隔离\/本地/);assert.match(failed,/项目模型保持不变/);assert.match(catalogFeedback('remote','',4,0),/没有识别出此类型/);assert.doesNotMatch(modelPicker([],'','global-model-id'),/fixture/);assert.match(modelPicker([],'','global-model-id'),/无可选项/);});
function fixture(){const p=model.makeProject('节点验收','standard'),e=model.makeEpisode(1,'第一集'),b=model.makeBeat(),s=model.makeSegment(b,1);e.segments=[s];p.episodes=[e];p.assets=[{id:'actor',name:'角色<一>',kind:'character',identity:'',voice:'',states:[],images:[{id:'old',role:'main',mediaPath:'old.png',source:'upload',createdAt:model.now()},{id:'new',role:'main',mediaPath:'new.png',source:'upload',createdAt:model.now()}]}];s.assetBindings=[{assetId:'actor',imageId:'old'}];return{p,e,s};}
test('asset canvas keeps one whole-sheet node and exposes local generation/comparison with segment context',()=>{const{p,e,s}=fixture(),before=JSON.stringify(p);const nodes=canvasAssets(p,e,s);assert.equal(nodes.length,1);assert.equal(nodes[0].image.id,'old');const html=renderCanvasAsset(nodes[0],e,s,'left:22px;top:33px',true);assert.match(html,/再生成候选/);assert.match(html,/比较与选用/);assert.match(html,/data-segment-id="/);assert.match(html,/角色&lt;一&gt;/);assert.match(html,/old.png/);assert.equal(JSON.stringify(p),before);});
test('asset media node identity survives selecting another version or changing state',()=>{const{p,e,s}=fixture();const first=canvasAssets(p,e,s)[0];p.assets[0].images[1].stateId='changed-state';s.assetBindings[0].imageId='new';const next=canvasAssets(p,e,s)[0];assert.equal(next.id,first.id);assert.equal(next.stateId,'changed-state');assert.equal(next.image.id,'new');});
test('canvas candidate workbench is a nonmodal dock preserving current selection and fee consent',()=>{const{p,e,s}=fixture();const html=candidatePanel(p,{input:{kind:'image',assetId:'actor',episodeId:e.id,segmentId:s.id,count:2},previews:[],requestIds:[],compareIds:['old','new']},[],'',true);assert.match(html,/canvas-dock/);assert.match(html,/aria-modal="false"/);assert.match(html,/当前选用/);assert.match(html,/审图通过/);assert.match(html,/预览换图影响并选用/);assert.match(html,/查看生成输入与费用/);assert.equal(s.assetBindings[0].imageId,'old');});
