import type {AgentWorkflow} from '../shared/agent-workflow';
import type {ProviderBilling} from '../shared/provider-billing';
import {billingQuote,modelPriceLabel,priceRange} from '../shared/provider-billing';
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]!);
export function billingPanel(billing?:ProviderBilling){
  const quota=billing?.quota,account=billing?.accountBalance;
  const quotaValue=quota&&!quota.unlimited&&billing?.quotaPerUnit&&billing.conversion?quota.available/billing.quotaPerUnit*billing.conversion:undefined;
  const display=account?`${account.available.toLocaleString('zh-CN',{maximumFractionDigits:2})} ${esc(account.currency)}`:
    quotaValue!==undefined?`${quotaValue.toLocaleString('zh-CN',{maximumFractionDigits:2})} ${esc(billing?.currency)}`:billing?.account?.pending?'等待登录完成':'登录后自动显示';
  const label=account||quotaValue===undefined?'账户余额':'密钥可用额度';
  const message=account?`${billing?.accountBalanceStale?'上次读取':'自动更新'} · ${esc(new Date(billing!.accountBalanceUpdatedAt||billing!.fetchedAt).toLocaleTimeString('zh-CN'))}${billing?.account?.name?' · '+esc(billing.account.name):''}`:
    billing?.account?.pending?'请在木木网页完成登录和同步授权。':billing?.account?.connected?esc(billing.accountBalanceError||'余额查询中…'):'点击上方“登录木木 API”，登录后余额会自动显示。';
  return `<div class="provider-billing"><div class="provider-balance-row"><div><span>${label}</span><strong aria-live="polite">${display}</strong></div></div><p class="muted">${message}</p>${billing?.accountBalanceStale?'<p class="muted">连接暂时中断，正在自动重试。</p>':''}${account?.matchesModelKey===false?'<p class="muted">当前模型密钥与登录账户不一致，请核对密钥所属账户。</p>':''}${account&&quotaValue!==undefined?`<details class="provider-key-limit"><summary>密钥限额</summary><p>${quotaValue.toLocaleString('zh-CN',{maximumFractionDigits:2})} ${esc(billing?.currency)}</p></details>`:''}</div>`;
}
export function agentPanel(flows:AgentWorkflow[],episodeId:string,billing?:ProviderBilling,delivery:'package'|'video'='package'){
  const flow=flows.find(w=>w.episodeId===episodeId&&!['cancelled','completed'].includes(w.status));
  if(!flow)return `<section class="agent-workflow"><h2>Agent 制作流程</h2><p>从本集已有进度继续。付费步骤先确认预算；核对候选、审图和审片沿用现有页面。</p><label>本次交付<select name="workflow-delivery"><option value="package" ${delivery==='package'?'selected':''}>分镜生产包</option><option value="video" ${delivery==='video'?'selected':''}>MP4 成片与剪映草稿</option></select></label><p class="muted">生产包完成后停止；选择成片才会进入视频生成与审片。提交次数上限用于限制请求数量，费用按实际用量结算。</p><div class="agent-limits">${(['text','image','video'] as const).map(kind=>`<label ${kind==='video'?`data-workflow-video-limit ${delivery==='package'?'hidden':''}`:''}>${({text:'文本',image:'图片',video:'视频'})[kind]}提交次数上限<input type="number" min="0" max="200" name="workflow-limit-${kind}" value="${({text:20,image:40,video:10})[kind]}"/></label>`).join('')}</div><button class="primary" data-action="workflow-start">启动本集流程</button>${flows.find(w=>w.episodeId===episodeId&&w.exportResult)?'<p>上一流程已有导出结果，可在导出页查看或继续另存。</p>':''}</section>`;
  const labels={running:'执行中',waiting_budget:'待预算确认',waiting_review:'待核对',paused:'已暂停',failed:'需要处理',completed:'已完成',cancelled:'已取消'};
  if(flow.taskId)return `<section class="agent-workflow"><div class="panel-head"><h2>Agent 制作流程</h2><span class="chip">${flow.status==='waiting_budget'?'等待 Agent 继续':labels[flow.status]}</span></div><h3>${esc(flow.step.label)}</h3><p>${esc(flow.error||flow.step.message)}</p><p class="muted">本流程使用已保存的任务额度。进度、剩余提交次数、暂停与恢复统一在 Agent 任务面板查看。</p><button class="primary" data-action="tab" data-tab="tasks">查看 Agent 任务</button>${['waiting_review','failed'].includes(flow.status)?`<button data-action="workflow-review" data-tab="${flow.step.tab}" data-segment-id="${esc(flow.step.segmentId||'')}">查看本集制作内容</button>`:''}</section>`;
  const quote=billingQuote(billing,flow.step.model||'',flow.step.submissions);
  return `<section class="agent-workflow" data-workflow-id="${esc(flow.id)}"><div class="panel-head"><h2>Agent 制作流程</h2><span class="chip">${labels[flow.status]}</span></div><h3>${esc(flow.step.label)}</h3><p role="status">${esc(flow.error||flow.step.message)}</p><p class="muted">已预约 / 上限：文本 ${flow.used.text}/${flow.limits.text} · 图片 ${flow.used.image}/${flow.limits.image} · 视频 ${flow.used.video}/${flow.limits.video}</p>
    ${flow.status==='waiting_budget'?`<div class="agent-budget"><h3>${flow.step.kind==='export'?'导出确认':'本步输入与预算'}</h3><p>模型：${esc(flow.step.model||'本地导出')} · 最多提交 ${flow.step.submissions} 次${flow.step.kind==='video'?' · 30 秒视频':''}</p>${flow.step.kind!=='export'?`<p>${quote.known?`本步预计：${priceRange(quote)} ${esc(quote.currency)}`:esc(modelPriceLabel(billing,flow.step.model||'','text'))+'；按实际用量结算。'}</p>${billingPanel(billing)}`:''}<details><summary>查看本步实际输入</summary><pre>${esc(JSON.stringify(flow.step.preview||flow.step.input||flow.step,null,2))}</pre></details><label class="agent-confirm"><input name="workflow-confirmed" type="checkbox"/>${flow.step.kind==='export'?(flow.step.task==='package'?'确认导出分镜生产包':'确认合成 MP4 并另存剪映草稿'):'已核对输入与额度，确认本步费用；无法估计时接受未知费用'}</label><button class="primary" data-action="workflow-authorize" data-id="${flow.id}">${flow.step.kind==='export'?'确认并导出':'确认预算并执行本步'}</button></div>`:''}
    <div class="actions">${flow.status==='waiting_review'||flow.status==='failed'?`<button class="primary" data-action="workflow-review" data-tab="${flow.step.tab}" data-segment-id="${esc(flow.step.segmentId||'')}">前往原有页面处理</button>`:''}${flow.status!=='running'&&flow.status!=='waiting_budget'?`<button data-action="workflow-control" data-id="${flow.id}" data-operation="resume">检查并继续</button>`:''}${flow.status!=='paused'?`<button data-action="workflow-control" data-id="${flow.id}" data-operation="pause">暂停流程</button>`:''}<button data-action="workflow-control" data-id="${flow.id}" data-operation="cancel">取消后续执行</button><button data-action="refresh-billing">刷新余额与价格</button></div><details><summary>流程记录 · ${flow.history.length} 步</summary>${flow.history.slice(-20).map(h=>`<p>${esc(h.label)} · ${esc(({running:'执行中',completed:'已完成',failed:'失败'})[h.status])}${h.error?' · '+esc(h.error):''}</p>`).join('')}</details></section>`;
}
