import type { AgentDashboard, AgentReadiness } from '../shared/agent-dashboard';
const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
const date = (value: string) => Number.isNaN(Date.parse(value)) ? '' : new Date(value).toLocaleString('zh-CN');
const taskStatus = { active: '授权有效', paused: '已暂停', expired: '授权已到期', revoked: '已撤回', configuration_changed: '配置已变化' };
const flowStatus = { running: '执行中', waiting_budget: '等待额度内继续', waiting_review: '等待内容核验', paused: '已暂停', failed: '需要处理失败结果', completed: '已完成', cancelled: '已取消' };
export function renderAgentReadiness(value?: AgentReadiness): string {
  if (!value) return '';
  const checks = value.checks.map(c => {
    const switchModel = value.projectId && c.canUseDefault ? `<div class="actions"><button data-action="use-project-default-model" data-project-id="${esc(value.projectId)}" data-model-kind="${esc(c.key)}" data-model-hash="${esc(c.modelHash)}" data-default-model-hash="${esc(c.defaultModelHash)}">本项目改用 ${esc(c.defaultModelId)}</button></div>` : '';
    return `<li><strong>${esc(c.label)}</strong><div>${c.ready ? '已就绪' : '待处理'} · ${esc(c.message)}${switchModel}</div></li>`;
  }).join('');
  return `<details class="agent-readiness" data-dashboard-key="readiness"><summary>本机准备检查 · ${value.missing.length ? '待补齐：' + esc(value.missing.join('、')) : '配置已就绪'}</summary><ul>${checks}</ul>${value.projectId ? '<p><button data-action="project-model-settings">查看／更改本项目模型</button></p>' : ''}<p class="muted">${esc(value.note)}</p></details>`;
}
export function renderAgentDashboard(value?: AgentDashboard): string {
  if (!value) return '<p role="status">正在读取任务进度…</p>';
  const active = value.tasks.filter(t => t.status === 'active').length;
  const recovery = value.scriptRecovery || [];
  const requests = value.modelRequests || [];
  return `<div class="agent-dashboard"><div class="page-title"><div><span class="eyebrow">Agent 制作</span><h2>任务与交付</h2><p>每段 ${value.rules.segmentDurationSec} 秒 · 每集 ${value.rules.minChapters}–${value.rules.maxChapters} 章</p></div><div class="actions"><button data-action="copy-task-context">复制接管／继续说明</button><button data-action="refresh-agent-dashboard">刷新进度</button></div></div>
    <p data-dashboard-summary role="status" aria-atomic="true">${active} 个有效任务 · ${value.tasks.filter(t => t.status === 'paused').length} 个暂停任务 · ${value.deliverables.filter(d => d.available).length} 份交付文件</p>${renderAgentReadiness(value.readiness)}
    ${recovery.length ? `<details class="panel" data-dashboard-key="script-recovery"><summary>已有剧本待核对 · ${recovery.length} 集</summary><p>保留已保存剧本，按集补齐原文、高光和逐字依据，再核对锁稿。可导入已有报告或让 Agent 依据完整原文补写；使用软件文本模型须有本次额度。</p>${recovery.map(e => `<article><strong>第${e.number}集 · ${esc(e.label)}</strong><p>${esc(e.message)}</p>${e.missing.length ? `<p class="muted">待补齐：${esc(e.missing.join('、'))}</p>` : ''}<button data-action="open-episode" data-id="${esc(e.episodeId)}">查看本集</button></article>`).join('')}</details>` : ''}
    <section class="panel"><h3>本次任务</h3><p class="muted">暂停会停止后续生成和 Agent 核验；已提交的请求可能继续返回结果。恢复沿用剩余额度，不重置消耗。</p><div class="agent-task-list">${value.tasks.map(t => `<article class="agent-task-card" data-task-card="${esc(t.id)}"><header><strong>${esc(t.agent)} · ${t.delivery === 'video' ? '成片' : '生产包'}</strong><span class="chip">${taskStatus[t.status]}</span></header><p>${esc(t.statement)}</p><p class="muted">${t.episodes.map(e => `第${e.number}集 · ${esc(e.title)}`).join('、')} · 授权到期 ${date(t.expiresAt)}</p>
      <dl class="agent-quota">${(['text', 'image', 'video'] as const).map(k => `<div><dt>${({ text: '文本', image: '图片', video: '视频' })[k]}提交</dt><dd>剩余 ${t.remaining[k]} / ${t.limits[k]}<small>已提交 ${t.used[k]} 次</small></dd></div>`).join('')}</dl>${t.maxAmount !== undefined ? `<p>费用预留 ${t.reservedAmount} / ${t.maxAmount} ${esc(t.currency)}<small class="muted"> · 预留数值不代表实际扣费</small></p>` : ''}
      <div class="actions">${!value.archived && t.status === 'active' ? `<button data-action="agent-task-control" data-task-id="${esc(t.id)}" data-operation="pause">暂停任务</button>` : ''}${!value.archived && t.status === 'paused' ? `<button class="primary" data-action="agent-task-control" data-task-id="${esc(t.id)}" data-operation="resume">恢复任务</button>` : ''}${!value.archived && !['revoked', 'expired'].includes(t.status) ? `<button data-action="agent-task-control" data-task-id="${esc(t.id)}" data-operation="revoke">撤回授权</button>` : ''}</div></article>`).join('') || '<p>还没有 Agent 任务。把接管说明、小说和交付要求发给 Agent，它会保存本次集数与额度，并从现有进度开始。</p>'}</div></section>
    <section class="panel"><h3>各集当前步骤</h3><div class="agent-flow-list">${value.workflows.map(w => `<article><header><strong>第${w.episodeNumber}集 · ${esc(w.step.label)}</strong><span class="chip">${flowStatus[w.status]}</span></header><p>${esc(w.step.message)}</p>${w.step.model ? `<p class="muted">当前步骤模型：${esc(w.step.model)}</p>` : ''}${w.error ? `<p>上次执行失败${w.lastAttempt?.model ? ' · ' + esc(w.lastAttempt.model) : ''}${w.lastAttempt?.at ? ' · ' + date(w.lastAttempt.at) : ''}：${esc(w.error)}</p>` : ''}<small class="muted">已完成 ${w.completedSteps} 个步骤 · ${date(w.updatedAt)}${w.taskId ? ' · 关联任务 ' + esc(w.taskId.slice(0, 8)) : ' · 软件手动流程'}</small><div><button data-action="open-episode" data-id="${esc(w.episodeId)}">查看本集</button></div></article>`).join('') || '<p>尚未开始工作流。</p>'}</div></section>
    ${requests.length ? `<details class="panel" data-dashboard-key="model-requests"><summary>最近模型请求 · ${requests.length} 条</summary><p class="muted">按实际提交记录核对，切换模型不会改写历史请求。</p>${requests.map(r => `<article><strong>${r.http?.model ? '已发出：' : '任务快照：'}${esc(r.http?.model || r.model || '未记录模型')}</strong><p>${esc(r.task)} · ${esc(r.status)}${r.http ? ' · HTTP ' + r.http.status : ''} · ${date(r.submittedAt)}</p><small class="muted">本机请求 ${esc(r.id)}${r.http?.requestId ? ' · 服务商请求 ' + esc(r.http.requestId) : ''}</small></article>`).join('')}</details>` : ''}
    <section class="panel"><h3>交付文件</h3>${value.deliverables.map(d => `<article class="agent-deliverable"><strong>第${d.episodeNumber}集 · ${({ package: '分镜生产包', mp4: 'MP4 成片', draft: '剪映草稿' })[d.kind]}</strong><p>${esc(d.path)}</p><div class="actions">${d.available ? `<button data-action="copy-export-path" data-path="${esc(d.path)}">复制文件位置</button>${d.url ? `<a class="button-link" href="${esc(d.url)}" target="_blank" rel="noopener">查看成片</a>` : ''}` : '<span>文件已移走或缺失，请核对原位置。</span>'}</div></article>`).join('') || '<p>完成核验并导出后，文件位置会出现在这里。</p>'}</section>
    <details class="panel" data-dashboard-key="reviews"><summary>Agent 核验记录 · 最近 ${value.reviews.length} 条</summary><p class="muted">记录使用 Agent 身份；内容核验不等于用户已验收。</p>${value.reviews.map(r => `<article class="agent-review"><strong>${esc(r.reviewer)} · ${r.status === 'completed' ? '已保存' : '未成功应用'}</strong><small>${date(r.at)} · ${esc(r.action)}</small><p>${esc(r.notes)}</p></article>`).join('') || '<p>暂无核验记录。</p>'}</details></div>`;
}
