import {renderAppNotice} from '../shared/ui-notice.js';
import type {Project} from '../shared/model.js';
import {requiresPortraitReference,isCharacterSheet} from '../shared/asset-references.js';
import {assetInputHash} from '../shared/generation.js';
export type CandidateInput={kind:'image'|'video';count:number;assetId?:string;stateId?:string;role?:string;sourceImageId?:string;episodeId?:string;segmentId?:string;feedback?:string};
export type CandidatePreview={input:CandidateInput;hash:string;model:{name:string;id:string};summary:Record<string,unknown>;cost:{known:boolean;maximumSubmissions:number;message:string};selection:string};
export type CandidateBatch={id:string;input:CandidateInput;paused?:boolean;cancelled?:boolean;items:{id:string;status:string;error?:string}[]};
export type CandidateWorkspace={input:CandidateInput;previews:CandidatePreview[];requestIds:string[];compareIds:string[];confirmed?:boolean;submitted?:boolean;uncertain?:boolean;pending?:boolean};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const media=(v:string)=>'/media/'+v.split('/').map(encodeURIComponent).join('/');
const statusLabel=(s:string)=>({queued:'排队待发送',running:'生成或查询中',completed:'已完成',failed:'失败，不自动重试',cancelled:'已取消',pending:'待审核',approved:'审核通过',rejected:'未通过',stale:'旧版本（描述已变）'}[s]||s);
export function candidatePanel(project:Project,workspace:CandidateWorkspace,batches:CandidateBatch[],message='',dock=false){
  const input=workspace.input,asset=project.assets?.find(a=>a.id===input.assetId),episode=project.episodes.find(e=>e.id===input.episodeId),segment=episode?.segments.find(s=>s.id===input.segmentId);
  const images=asset?.images.filter(i=>(i.role||'main')===(input.role||'main')&&(i.stateId||'')===(input.stateId||''))||[];
  const videos=segment?.artifacts.filter(a=>a.kind==='video')||[];
  const choices=input.kind==='image'?images.map(i=>({id:i.id,mediaPath:i.mediaPath,status:i.inputHash&&i.inputHash!==assetInputHash(project,asset!.id,i.stateId)?'stale':i.review?.status||'pending'})):videos.map(v=>({id:v.id,mediaPath:v.mediaPath||'',status:v.userAcceptance?.status==='accepted'?'用户验收通过':v.review?.status||'pending'}));
  const selected=input.kind==='video'?segment?.selected.video:segment?.assetBindings?.find(b=>b.assetId===asset?.id)?.imageId;
  const targets=project.episodes.flatMap(e=>e.segments.map(s=>({value:e.id+':'+s.id,label:'EP'+e.number+' · 片段'+s.number})));
  const relevant=batches.filter(b=>b.input.kind===input.kind&&(input.kind==='image'?b.input.assetId===input.assetId:b.input.segmentId===input.segmentId));
  return `<div class="candidate-overlay ${dock?'canvas-dock':''}"><section class="candidate-workbench" role="dialog" aria-modal="${dock?'false':'true'}" aria-label="候选生成与比较" ${asset?`data-asset-id="${asset.id}"`:''}><div class="panel-head"><div><h2>${input.kind==='image'?esc(asset?.name)+' · 图片候选':'片段'+segment?.number+' · 视频候选'}</h2><p>不必先判废，也不必修改输入。当前选用保持不变，满意后再明确选用。</p></div><button data-action="candidate-close">关闭</button></div>
  ${renderAppNotice(message)}<div class="candidate-toolbar">${input.kind==='image'?`<label>返修原图<select name="candidate-source-image" ${workspace.pending||workspace.uncertain?'disabled':''}><option value="">不指定返修原图</option>${images.map((i,n)=>`<option value="${i.id}" ${input.sourceImageId===i.id?'selected':''}>v${n+1} · ${esc(statusLabel(i.review?.status||'pending'))} · ${i.id.slice(0,8)}</option>`).join('')}</select></label><small>返修时选择原图，模型会同时接收图片和修改要求。人物返修输出仍为完整四视图，剧情状态沿用已审核身份参考。</small>`:''}<label>可选视觉偏好（留空表示同输入再试，不改正式剧情）<textarea name="candidate-feedback" maxlength="500" ${workspace.pending||workspace.uncertain?'disabled':''}>${esc(input.feedback)}</textarea></label><label>再生成<select name="candidate-count" ${workspace.pending||workspace.uncertain?'disabled':''}>${[1,2,3,4].map(n=>`<option value="${n}" ${input.count===n?'selected':''}>${n}版</option>`).join('')}</select></label><button data-action="candidate-preview" ${workspace.pending||workspace.uncertain?'disabled':''}>查看生成输入与费用</button>${workspace.previews.length?`<div class="candidate-budget"><p>模型：${esc(workspace.previews[0].model.name)} · ${esc(workspace.previews[0].model.id)}；本次最多提交 <strong>${workspace.previews.reduce((n,p)=>n+p.cost.maximumSubmissions,0)}</strong> 次${input.kind==='video'?'，每版固定30秒':''}。</p><p>${esc(workspace.previews[0].cost.message)}</p>${input.kind==='video'?`<p>完整提交提示词：${esc(workspace.previews[0].summary.promptCharacters)} 字${workspace.previews[0].summary.promptLimit?` / 模型上限 ${esc(workspace.previews[0].summary.promptLimit)} 字`:''}；包含参考修正和本次视觉偏好。</p>`:''}<details><summary>实际使用的输入（点击展开）</summary>${workspace.previews.map(p=>`<pre>${esc(JSON.stringify(p.summary,null,2))}</pre>`).join('')}</details><label><input name="candidate-cost-confirmed" type="checkbox" ${workspace.confirmed?'checked':''}/>已核对输入、数量，接受费用金额未知并允许这些请求</label><button class="primary" data-action="candidate-submit" ${workspace.pending?'disabled':''}>${workspace.pending?'提交中…':workspace.uncertain?'用原确认号查询/重传':'确认生成候选'}</button><small>取消只阻止尚未提交的候选；已提交任务不能保证退款。</small></div>`:''}</div>
  ${relevant.some(b=>b.items.some(i=>i.status==='failed'))?`<p class="warning">失败结果保留。先核对错误和费用；新尝试会新增候选，并再次确认费用。</p><button data-action="candidate-retry-preview" ${workspace.pending||workspace.uncertain?'disabled':''}>准备单版重试（先预览费用）</button>`:''}${relevant.length?`<div class="candidate-progress">${relevant.slice(0,6).map(b=>`<article><strong>${b.items.filter(i=>i.status==='completed').length}/${b.items.length} 完成${b.cancelled?' · 已取消剩余':b.paused?' · 已暂停':''}</strong><span>${b.items.map((i,n)=>`${n+1}:${esc(statusLabel(i.status))}`).join(' · ')}</span>${b.items.filter(i=>i.error).map(i=>`<p class="warning">${esc(i.error)}</p>`).join('')}${!b.cancelled&&b.items.some(i=>['queued','running'].includes(i.status))?`<button data-action="candidate-control" data-batch-id="${b.id}" data-operation="${b.paused?'resume':'pause'}">${b.paused?'继续未提交候选':'暂停后续'}</button><button data-action="candidate-control" data-batch-id="${b.id}" data-operation="cancel">取消剩余</button>`:''}</article>`).join('')}</div>`:''}
  ${workspace.uncertain?'<button data-action="candidate-query-only">停止重传，只查看已预约批次</button>':''}<button data-action="candidate-go-tasks">查看后台任务/未知计费对账</button><button data-action="candidate-go-segment">查看/制作所选片段</button><h3>同屏比较与选用</h3><p>勾选最多3版比较；旧版本始终保留。审图通过不等于替换片段参考图。</p><div class="candidate-choices">${choices.map((c,n)=>`<button data-action="candidate-compare" data-id="${c.id}" class="${workspace.compareIds.includes(c.id)?'chosen':''}">v${n+1} · ${c.id===selected?'当前选用 · ':''}${esc(statusLabel(c.status))}</button>`).join('')||'尚无候选'}</div>
  <div class="candidate-comparison">${choices.filter(c=>workspace.compareIds.includes(c.id)).map(c=>input.kind==='image'?`<figure data-image-id="${c.id}"><img src="${media(c.mediaPath)}" alt="候选参考图"/><figcaption>${esc(c.id.slice(0,8))} · ${esc(statusLabel(c.status))}</figcaption>${(['identity','state','shape','clothing'] as const).map(k=>`<label><input type="checkbox" name="asset-review-check" value="${k}" ${images.find(i=>i.id===c.id)?.review?.checks[k]?'checked':''}/> ${esc(({identity:'身份',state:'剧情状态',shape:'形态',clothing:'服饰'})[k])}</label>`).join('')}<button data-action="asset-image-review" data-status="approved" ${c.status==='stale'?'disabled':''}>审图通过</button><button data-action="asset-image-review" data-status="rejected">判废</button><label>用于片段<select name="candidate-binding-target">${targets.map(t=>`<option value="${t.value}" ${t.value===input.episodeId+':'+input.segmentId?'selected':''}>${esc(t.label)}</option>`).join('')}</select></label><button data-action="candidate-use-image" data-image-id="${c.id}" ${c.status==='approved'&&targets.length&&(!asset||!requiresPortraitReference(asset)||isCharacterSheet(images.find(i=>i.id===c.id)))?'':'disabled'}>预览换图影响并选用</button></figure>`:`<article data-segment-id="${segment!.id}" data-artifact-id="${c.id}"><video controls preload="metadata" src="${media(c.mediaPath)}"></video><p>${c.id===selected?'当前选用':'候选'} · ${esc(statusLabel(c.status))}</p><button data-action="select-artifact" data-segment-id="${segment!.id}" data-kind="video" data-artifact-id="${c.id}" ${c.status==='rejected'?'disabled':''}>选用此版</button><button data-action="candidate-review-video" data-id="${c.id}">进入逐句审片</button></article>`).join('')}</div>
  ${input.kind==='image'?'<button data-action="candidate-go-assets">修改资产描述或剧情状态</button>':'<button data-action="candidate-go-segment">修改分镜或参考图</button>'}</section></div>`;
}
