import type {ProjectProgress,ProgressDelivery} from '../shared/project-progress';
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const workflowLabels:Record<string,string>={running:'正在执行',waiting_budget:'等待额度确认',waiting_review:'等待核对',paused:'已暂停',failed:'需要处理'};
export function renderHomeProgress(progress?:ProjectProgress,loading=false,error='',delivery:ProgressDelivery='package',targetEpisodes=1,page=1){
  if(!progress)return `<div class="home-progress-empty" role="status">${esc(error||'正在读取已有制作进度…')}${error?'<button data-action="home-progress-refresh">重新读取</button>':''}</div>`;
  const t=progress.totals,limit=Math.max(1,Math.min(10,Math.floor(targetEpisodes)||1));
  const scope=progress.episodes.slice(0,limit),next=scope.find(e=>!e.ready[delivery])||scope[0],step=next?.next[delivery];
  const pages=Math.max(1,Math.ceil(progress.episodes.length/8)),current=Math.max(1,Math.min(pages,page)),visible=progress.episodes.slice((current-1)*8,current*8);
  const open=(episodeId:string,tab:string,segmentId='')=>`data-action="home-progress-open" data-project-id="${esc(progress.projectId)}" data-episode-id="${esc(episodeId)}" data-tab="${esc(tab)}" data-segment-id="${esc(segmentId)}"`;
  const metrics=[['锁定剧本',`${t.scriptsLocked} / ${t.episodes} 集`,'按当前剧本版本统计'],['已存分镜',`${t.segments} 个片段`,`${t.storyboardsReviewed} 个已逐镜核对`],['已存提示词',`${t.promptsSaved} 个片段`,`${t.promptsCurrent} 个当前版本可用`],['已存视频',`${t.videosSaved} 个片段`,`${t.videosApproved} 个当前选用已审核 / 验收`],['项目资产',`${t.assets} 项`,`${t.referenceImages} 张参考图，${t.referenceImagesCurrent} 张当前已审核`],['五层放行',`${t.auditedEpisodes} / ${t.episodes} 集`,'保留已有记录，版本变化需重新核对']];
  const flow=next&&progress.workflows.find(w=>w.episodeId===next.id);
  return `<div class="home-progress-heading"><h3>已有制作进度</h3><button data-action="home-progress-refresh" aria-busy="${loading}">${loading?'读取中…':'刷新进度'}</button></div>
    ${error?`<p class="home-progress-warning" role="status">${esc(error)} · 下方保留上次读取的记录。</p>`:''}
    <div class="home-progress-next"><span>本次接续 · 前 ${limit} 集 · ${delivery==='package'?'分镜生产包':'成片'}</span>${next&&step?`<strong>EP ${next.number} · ${esc(step.label)}</strong><p>${esc(step.message)}</p>${flow?`<small>${esc(workflowLabels[flow.status]||flow.status)} · ${esc(flow.error||flow.label)}${flow.message?` · ${esc(flow.message)}`:''}</small>`:''}<button ${open(next.id,step.tab,step.segmentId)}>查看接续位置 →</button>`:'<strong>先按原文章节建立分集</strong><p>完整小说与项目记录会保留，建立分集后再接续制作。</p><button data-action="home-open-project" data-id="'+esc(progress.projectId)+'">查看项目</button>'}<small>Agent 将读取并复用已有成果；启动范围仍以本次填写的集数与授权为准。</small></div>
    <p class="home-progress-source">原文已确认 ${t.sourceReviewed} 集 · 高光已核对 ${t.highlightReviewed} 集</p>
    <div class="home-progress-metrics">${metrics.map(([label,value,note])=>`<div><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`).join('')}</div>
    ${visible.length?`<div class="home-progress-episodes"><h4>各集进度</h4>${visible.map(episode=>`<button class="home-progress-episode" ${open(episode.id,episode.next[delivery].tab,episode.next[delivery].segmentId)}><span><strong>EP ${episode.number}</strong><span title="${esc(episode.title)}">${esc(episode.title)}</span></span><small>${episode.scriptLocked?'剧本已锁定':'剧本待核对'} · ${episode.segments} 片段 · 分镜核对 ${episode.storyboardsReviewed} · 提示词可用 ${episode.promptsCurrent} · 视频通过 ${episode.videosApproved}</small><span class="home-progress-stage">${esc(episode.next[delivery].label)} →</span></button>`).join('')}${pages>1?`<div class="home-progress-pager"><button data-action="home-progress-page" data-direction="previous" data-page="${current-1}" ${current===1?'disabled':''}>上一页</button><span>${current} / ${pages} · 共 ${t.episodes} 集</span><button data-action="home-progress-page" data-direction="next" data-page="${current+1}" ${current===pages?'disabled':''}>下一页</button></div>`:''}</div>`:''}
    ${progress.deliverables.length?`<p class="home-progress-deliveries">已有 ${progress.deliverables.filter(d=>d.available).length} 份可访问的导出记录${progress.deliverables.some(d=>!d.available)?'，部分文件已移动':''}；请在项目中核对交付版本。</p>`:''}
    <p class="home-progress-note">进度来自项目保存的内容。历史版本、未核对候选与未选用视频保留在项目中，不计为当前放行。</p>`;
}
